#!/usr/bin/env python
"""
Time-resolved audit of explicit vapor composition drift.

This reads a profile CSV generated by dynamic_run_scaffold_v1 and tracks vapor
RHS material terms, K mismatch, and vapor target mismatch across logged times.
It is intentionally read-only and does not call the model RHS.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple


TERM_PREFIXES = {
    "transport_in": "tray_V_transport_in_lbmolps_",
    "transport_out": "tray_V_transport_out_lbmolps_",
    "feed": "tray_V_feed_lbmolps_",
    "terminal_adjust": "tray_V_terminal_adjust_lbmolps_",
    "holdup_relax": "tray_V_holdup_relax_lbmolps_",
    "equilibrium_transfer": "tray_V_equilibrium_transfer_lbmolps_",
}


def _finite_float(value: Any) -> float:
    try:
        out = float(value)
    except Exception:
        return math.nan
    return out if math.isfinite(out) else math.nan


def _read_csv(path: str | Path) -> List[Dict[str, str]]:
    with Path(path).open(newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def _component_labels(row: Dict[str, str]) -> List[str]:
    prefix = "tray_V_final_rhs_lbmolps_"
    labels = [key[len(prefix) :] for key in row.keys() if key.startswith(prefix)]
    return sorted(labels)


def _dominant_term(terms: Dict[str, float]) -> Tuple[str, float]:
    finite = {k: v for k, v in terms.items() if math.isfinite(v)}
    if not finite:
        return "", math.nan
    key = max(finite, key=lambda k: abs(float(finite[k])))
    return key, float(finite[key])


def _stage_filter(value: Optional[str]) -> Optional[set[int]]:
    if value is None or not str(value).strip():
        return None
    out: set[int] = set()
    for item in str(value).split(","):
        item = item.strip()
        if not item:
            continue
        out.add(int(item))
    return out


def _time_filter(value: Optional[str]) -> Optional[set[float]]:
    if value is None or not str(value).strip():
        return None
    out: set[float] = set()
    for item in str(value).split(","):
        item = item.strip()
        if not item:
            continue
        out.add(float(item))
    return out


def _time_allowed(t: float, allowed: Optional[set[float]], tol: float = 1.0e-6) -> bool:
    if allowed is None:
        return True
    return any(abs(float(t) - float(a)) <= tol for a in allowed)


def _safe_abs_ratio(num: float, den: float) -> float:
    if not math.isfinite(num) or not math.isfinite(den) or abs(den) <= 1.0e-300:
        return math.nan
    return abs(float(num) / float(den))


def _boundary_rows_by_time(rows: Iterable[Dict[str, str]]) -> Dict[float, Dict[str, str]]:
    out: Dict[float, Dict[str, str]] = {}
    for row in rows:
        node_type = str(row.get("node_type", "")).strip().lower()
        if node_type not in {"distillate_drum", "top_drum", "top"}:
            continue
        t = _finite_float(row.get("time_s"))
        if math.isfinite(t):
            out[float(t)] = row
    return out


def _time_diag(row: Dict[str, str], boundary_by_time: Dict[float, Dict[str, str]], t: float, key: str) -> float:
    value = _finite_float(row.get(key))
    if math.isfinite(value):
        return value
    boundary = boundary_by_time.get(float(t))
    if boundary is not None:
        return _finite_float(boundary.get(key))
    return math.nan


def audit_profile(
    profile_csv: str | Path,
    *,
    stages: Optional[Sequence[int]] = None,
    times: Optional[Sequence[float]] = None,
    denom_floor_lbmol: float = 1.0,
    top_n: int = 15,
) -> Dict[str, Any]:
    rows_all = _read_csv(profile_csv)
    stage_rows = [
        row
        for row in rows_all
        if str(row.get("node_type", "")).strip().lower() == "stage"
        and math.isfinite(_finite_float(row.get("time_s")))
        and math.isfinite(_finite_float(row.get("stage")))
    ]
    if not stage_rows:
        raise ValueError("No stage rows found in profile CSV")
    labels = _component_labels(stage_rows[0])
    if not labels:
        raise ValueError("No tray_V_final_rhs component columns found")
    boundary_by_time = _boundary_rows_by_time(rows_all)

    stage_set = set(int(s) for s in stages) if stages else None
    time_set = set(float(t) for t in times) if times else None
    floor = max(float(denom_floor_lbmol), 0.0)

    records: List[Dict[str, Any]] = []
    stage_summary_map: Dict[Tuple[float, int], Dict[str, Any]] = {}
    time_summary_map: Dict[float, Dict[str, Any]] = {}

    for row in stage_rows:
        t = _finite_float(row.get("time_s"))
        stage = int(round(_finite_float(row.get("stage"))))
        if stage_set is not None and stage not in stage_set:
            continue
        if not _time_allowed(t, time_set):
            continue
        mv = _finite_float(row.get("MV_lbmol"))
        if not math.isfinite(mv):
            mv = 0.0

        stage_key = (float(t), int(stage))
        if stage_key not in stage_summary_map:
            energy_over_hc = _finite_float(row.get("stage_energy_resid_over_heat_capacity_F_per_s"))
            if not math.isfinite(energy_over_hc):
                energy_over_hc = _safe_abs_ratio(
                    _finite_float(row.get("stage_energy_balance_resid_BTUps")),
                    _finite_float(row.get("tray_effective_heat_capacity_BTU_per_F")),
                )
            stage_summary_map[stage_key] = {
                "time_s": float(t),
                "stage_1based": int(stage),
                "max_abs_final_rhs_lbmolps": 0.0,
                "max_relative_rhs_per_s": 0.0,
                "max_abs_y_minus_target": 0.0,
                "max_abs_ln_K_state_over_K_thermo": 0.0,
                "max_abs_energy_resid_over_heat_capacity_F_per_s": energy_over_hc,
                "dT_energy_raw_F_per_s": _finite_float(row.get("dT_energy_raw_F_per_s")),
                "V_condensed_in_lbmolph": _time_diag(row, boundary_by_time, t, "V_condensed_in_lbmolph"),
                "P_top_drum_psia": _time_diag(row, boundary_by_time, t, "P_top_drum_psia"),
                "V_to_top_drum_lbmolph": _time_diag(row, boundary_by_time, t, "V_to_top_drum_lbmolph"),
                "V_to_top_drum_pressure_gate_scale": _time_diag(
                    row, boundary_by_time, t, "V_to_top_drum_pressure_gate_scale"
                ),
            }
        if float(t) not in time_summary_map:
            time_summary_map[float(t)] = {
                "time_s": float(t),
                "max_abs_final_rhs_lbmolps": 0.0,
                "max_relative_rhs_per_s": 0.0,
                "max_abs_y_minus_target": 0.0,
                "max_abs_ln_K_state_over_K_thermo": 0.0,
                "worst_stage_1based": None,
                "worst_component": "",
                "V_condensed_in_lbmolph": _time_diag(row, boundary_by_time, t, "V_condensed_in_lbmolph"),
                "P_top_drum_psia": _time_diag(row, boundary_by_time, t, "P_top_drum_psia"),
                "V_to_top_drum_lbmolph": _time_diag(row, boundary_by_time, t, "V_to_top_drum_lbmolph"),
                "V_to_top_drum_pressure_gate_scale": _time_diag(
                    row, boundary_by_time, t, "V_to_top_drum_pressure_gate_scale"
                ),
            }

        for label in labels:
            y = _finite_float(row.get(f"y_{label}"))
            y_target = _finite_float(row.get(f"y_target_{label}"))
            k_ratio = _finite_float(row.get(f"K_state_over_K_thermo_{label}"))
            final_rhs = _finite_float(row.get(f"tray_V_final_rhs_lbmolps_{label}"))
            pre_rhs = _finite_float(row.get(f"tray_V_pre_equilibrium_rhs_lbmolps_{label}"))
            terms = {
                name: _finite_float(row.get(f"{prefix}{label}"))
                for name, prefix in TERM_PREFIXES.items()
            }
            dominant_name, dominant_value = _dominant_term(terms)
            inventory = max(mv * y, 0.0) if math.isfinite(y) else 0.0
            rel = abs(final_rhs) / max(abs(inventory) + floor, 1.0e-300) if math.isfinite(final_rhs) else math.nan
            y_gap = abs(y - y_target) if math.isfinite(y) and math.isfinite(y_target) else math.nan
            ln_k_gap = abs(math.log(k_ratio)) if math.isfinite(k_ratio) and k_ratio > 0.0 else math.nan

            record = {
                "time_s": float(t),
                "stage_1based": int(stage),
                "component": label,
                "inventory_lbmol": inventory,
                "relative_rhs_per_s": rel,
                "final_rhs_lbmolps": final_rhs,
                "pre_equilibrium_rhs_lbmolps": pre_rhs,
                "y_state": y,
                "y_target": y_target,
                "abs_y_minus_target": y_gap,
                "abs_ln_K_state_over_K_thermo": ln_k_gap,
                "dominant_term": dominant_name,
                "dominant_term_lbmolps": dominant_value,
                "V_condensed_in_lbmolph": _time_diag(row, boundary_by_time, t, "V_condensed_in_lbmolph"),
                "P_top_drum_psia": _time_diag(row, boundary_by_time, t, "P_top_drum_psia"),
                "stage_energy_resid_over_heat_capacity_F_per_s": _safe_abs_ratio(
                    _finite_float(row.get("stage_energy_balance_resid_BTUps")),
                    _finite_float(row.get("tray_effective_heat_capacity_BTU_per_F")),
                ),
                "dT_energy_raw_F_per_s": _finite_float(row.get("dT_energy_raw_F_per_s")),
                **{f"{name}_lbmolps": value for name, value in terms.items()},
            }
            records.append(record)

            stage_summary = stage_summary_map[stage_key]
            time_summary = time_summary_map[float(t)]
            if math.isfinite(final_rhs):
                stage_summary["max_abs_final_rhs_lbmolps"] = max(
                    float(stage_summary["max_abs_final_rhs_lbmolps"]), abs(float(final_rhs))
                )
                time_summary["max_abs_final_rhs_lbmolps"] = max(
                    float(time_summary["max_abs_final_rhs_lbmolps"]), abs(float(final_rhs))
                )
            if math.isfinite(rel):
                stage_summary["max_relative_rhs_per_s"] = max(
                    float(stage_summary["max_relative_rhs_per_s"]), abs(float(rel))
                )
                if abs(float(rel)) > float(time_summary["max_relative_rhs_per_s"]):
                    time_summary["max_relative_rhs_per_s"] = abs(float(rel))
                    time_summary["worst_stage_1based"] = int(stage)
                    time_summary["worst_component"] = str(label)
            if math.isfinite(y_gap):
                stage_summary["max_abs_y_minus_target"] = max(
                    float(stage_summary["max_abs_y_minus_target"]), float(y_gap)
                )
                time_summary["max_abs_y_minus_target"] = max(
                    float(time_summary["max_abs_y_minus_target"]), float(y_gap)
                )
            if math.isfinite(ln_k_gap):
                stage_summary["max_abs_ln_K_state_over_K_thermo"] = max(
                    float(stage_summary["max_abs_ln_K_state_over_K_thermo"]), float(ln_k_gap)
                )
                time_summary["max_abs_ln_K_state_over_K_thermo"] = max(
                    float(time_summary["max_abs_ln_K_state_over_K_thermo"]), float(ln_k_gap)
                )

    records.sort(
        key=lambda r: (
            abs(float(r["relative_rhs_per_s"]))
            if math.isfinite(float(r.get("relative_rhs_per_s", math.nan)))
            else -math.inf
        ),
        reverse=True,
    )
    stage_summaries = sorted(stage_summary_map.values(), key=lambda r: (float(r["time_s"]), int(r["stage_1based"])))
    time_summaries = sorted(time_summary_map.values(), key=lambda r: float(r["time_s"]))

    return {
        "profile_csv": str(Path(profile_csv).resolve()),
        "stages": sorted(stage_set) if stage_set is not None else "all",
        "times": sorted(time_set) if time_set is not None else "all",
        "component_labels": labels,
        "summary_by_time": time_summaries,
        "summary_by_stage_time": stage_summaries,
        "top_component_records": records[: max(int(top_n), 1)],
        "component_records": records,
    }


def _fmt(value: Any) -> str:
    try:
        v = float(value)
    except Exception:
        return "" if value is None else str(value)
    if not math.isfinite(v):
        return ""
    return f"{v:.6g}"


def _table(rows: List[Dict[str, Any]], fields: List[str]) -> List[str]:
    lines = ["| " + " | ".join(fields) + " |", "|" + "|".join(["---"] * len(fields)) + "|"]
    for row in rows:
        lines.append("| " + " | ".join(_fmt(row.get(field, "")) for field in fields) + " |")
    return lines


def write_markdown(report: Dict[str, Any], path: str | Path) -> None:
    lines: List[str] = [
        "# Time-Resolved Vapor Drift Audit",
        "",
        f"Profile: `{report['profile_csv']}`",
        f"Stages: `{report['stages']}`",
        "",
        "## Summary By Time",
    ]
    lines.extend(
        _table(
            report["summary_by_time"],
            [
                "time_s",
                "max_relative_rhs_per_s",
                "max_abs_final_rhs_lbmolps",
                "max_abs_y_minus_target",
                "max_abs_ln_K_state_over_K_thermo",
                "worst_stage_1based",
                "worst_component",
                "V_condensed_in_lbmolph",
                "P_top_drum_psia",
                "V_to_top_drum_lbmolph",
                "V_to_top_drum_pressure_gate_scale",
            ],
        )
    )
    lines.extend(["", "## Summary By Selected Stage And Time"])
    lines.extend(
        _table(
            report["summary_by_stage_time"],
            [
                "time_s",
                "stage_1based",
                "max_relative_rhs_per_s",
                "max_abs_final_rhs_lbmolps",
                "max_abs_y_minus_target",
                "max_abs_ln_K_state_over_K_thermo",
                "max_abs_energy_resid_over_heat_capacity_F_per_s",
                "dT_energy_raw_F_per_s",
                "V_condensed_in_lbmolph",
                "P_top_drum_psia",
            ],
        )
    )
    lines.extend(["", "## Worst Component Records"])
    lines.extend(
        _table(
            report["top_component_records"],
            [
                "time_s",
                "stage_1based",
                "component",
                "relative_rhs_per_s",
                "final_rhs_lbmolps",
                "pre_equilibrium_rhs_lbmolps",
                "abs_y_minus_target",
                "abs_ln_K_state_over_K_thermo",
                "dominant_term",
                "dominant_term_lbmolps",
                "transport_in_lbmolps",
                "transport_out_lbmolps",
                "equilibrium_transfer_lbmolps",
            ],
        )
    )
    lines.append("")
    Path(path).write_text("\n".join(lines), encoding="utf-8")


def write_csv(rows: Iterable[Dict[str, Any]], path: str | Path) -> None:
    rows = list(rows)
    if not rows:
        Path(path).write_text("", encoding="utf-8")
        return
    fields = list(rows[0].keys())
    with Path(path).open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", required=True, help="Profile CSV with vapor RHS diagnostics")
    parser.add_argument("--stages", default=None, help="Comma-separated 1-based stages to track; default all")
    parser.add_argument("--times", default=None, help="Comma-separated times to track; default all logged times")
    parser.add_argument("--denom-floor-lbmol", type=float, default=1.0)
    parser.add_argument("--top-n", type=int, default=15)
    parser.add_argument("--out-json", required=True)
    parser.add_argument("--out-md", required=True)
    parser.add_argument("--out-csv", default=None, help="Optional full component-record CSV")
    args = parser.parse_args()

    report = audit_profile(
        args.profile,
        stages=sorted(_stage_filter(args.stages) or []),
        times=sorted(_time_filter(args.times) or []),
        denom_floor_lbmol=args.denom_floor_lbmol,
        top_n=args.top_n,
    )
    Path(args.out_json).write_text(json.dumps(report, indent=2), encoding="utf-8")
    write_markdown(report, args.out_md)
    if args.out_csv:
        write_csv(report["component_records"], args.out_csv)


if __name__ == "__main__":
    main()
