"""
dwsim_compounds_v2.py

Dynamic Distillation - DWSIM Compound Reference

PURPOSE
-------
Provide authoritative DWSIM compound names used for component validation
and canonicalization paths.

INPUTS
------
- None (static reference module)

OUTPUTS
-------
- DWSIM_COMPOUNDS ordered list
- DWSIM_COMPOUND_SET membership set
- simple helper lookups for validation/diagnostics

ASSUMPTIONS & CONSTRAINTS
-------------------------
- Names are case/format sensitive at the source list level.
- Alias handling is implemented in compound_registry_v1.
"""

from __future__ import annotations

from typing import Iterable

# Ordered list (as provided in the source list)
DWSIM_COMPOUNDS = [
    "2-ethyl-p-xylene",
    "2-heptanone",
    "2-hexanone",
    "2-Methoxy-2-Methyl-Heptane",
    "2-methyl-1-butanol",
    "2-methyl-1-butene",
    "1,2-propylene oxide",
    "1,2,3-trimethylbenzene",
    "1,2,3,4-tetramethylbenzene",
    "1,2,3,5-tetramethylbenzene",
    "1,2,4-trichlorobenzene",
    "1,2,4-trimethylbenzene",
    "1-pentanol",
    "1-pentene",
    "1-phenylnaphthalene",
    "1-propanol",
    "1-undecene",
    "1,1-dichloroethane",
    "1-hexene",
    "1-methyl-1-ethylcyclopentane",
    "1-methyl-3-n-propylbenzene",
    "1-methyl-4-n-propylbenzene",
    "1-methylindene",
    "1-methylnaphthalene",
    "ChemSep",
    "1-butanol",
    "1-butene",
    "1-heptanol",
    "2-methyl-1-propanol",
    "2-methyl-2-butanol",
    "2-methyl-1-heptene",
    "2-methyl-1-pentene",
    "1,4-butanediol",
    "1,4-dioxane",
    "2-butanol",
    "2-ethyl-m-xylene",
    "1,2,4,5-tetramethylbenzene",
    "1,3-butadiene",
    "1,1-dimethylcyclopentane",
    "1,1,2-trichloroethane",
    "1,2-butadiene",
    "1,2-dichloroethane",
    "1,1-dimethylcyclohexane",
    "1-nitrobutane",
    "1-nitropropane",
    "1-nonene",
    "1-octene",
    "1-heptene",
    "1-hexanol",
    "3-methylheptane",
    "3-methylhexane",
    "3-methylnonane",
    "3-methyloctane",
    "2,4,4-trimethylhexane",
    "2,4,6-trinitrotoluene",
    "2,5-dimethylhexane",
    "2,5-dinitrotoluene",
    "2,6-dinitrotoluene",
    "3-ethylheptane",
    "2,2,4-trimethylpentane",
    "2,2,4,4-tetramethylpentane",
    "2,2,5-trimethylhexane",
    "2,3-dimethylbutane",
    "2,3-dimethylhexane",
    "2,3-dimethylpentane",
    "2-pentanone",
    "2,2-dimethyl-1-propanol",
    "2,2-dimethylbutane",
    "2,2-dimethylheptane",
    "2,2-dimethylhexane",
    "2,2-dimethyloctane",
    "2-methyl-2-propanol",
    "2-methyl-3-ethylpentane",
    "2-methylheptane",
    "2-methylhexane",
    "2-methylindene",
    "2-methylnaphthalene",
    "3-heptanone",
    "3-hexanone",
    "3-methyl-1-butene",
    "3-methyl-3-ethylpentane",
    "3-ethylhexane",
    "3-ethylpentane",
    "2,3,4-trimethylpentane",
    "2,4-dimethylhexane",
    "2,4-dimethylpentane",
    "2,4-dinitrotoluene",
    "2,3,3-trimethylpentane",
    "2,3,3,4-tetramethylpentane",
    "2,2,3-trimethylpentane",
    "2,2,3,3-tetramethylbutane",
    "2,2,3,3-tetramethylpentane",
    "2,2,3,4-tetramethylpentane",
    "2,2-dimethylpentane",
    "2,2,3-trimethylbutane",
    "2-methylpentane",
    "2-methylpropanal",
    "2-nitropropane",
    "2-pentanol",
    "2-methylnonane",
    "2-methyloctane",
    "2-methyl-2-butene",
    "2-Methyl-2-Heptanol",
    "Carbon disulfide",
    "Carbon monoxide",
    "Carbon tetrachloride",
    "Carbonyl sulfide",
    "Chlorine",
    "Chloroform",
    "Ammonia",
    "Aniline",
    "Anisole",
    "Argon",
    "Benzene",
    "Benzoic acid",
    "Acenaphthene",
    "Acetaldehyde",
    "Acetic acid",
    "Acetic anhydride",
    "Acetone",
    "Acetonitrile",
    "3,4-dinitrotoluene",
    "3,5-dinitrotoluene",
    "4-ethyl-m-xylene",
    "4-ethyl-o-xylene",
    "4-heptanone",
    "4-methyl-cis-2-pentene",
    "3-methylpentane",
    "3-pentanone",
    "Cis-1,2-dimethylcyclopentane",
    "Cis-1,3-dimethylcyclohexane",
    "Chrysene",
    "Cis-1,2-dimethylcyclohexane",
    "Bromobenzene",
    "Butanal",
    "Butyl vinyl ether",
    "Carbon dioxide",
    "Biphenyl",
    "Bromine",
    "Acrylic acid",
    "Acrylonitrile",
    "Adipic acid",
    "Air",
    "Acetyl chloride",
    "Acetylene",
    "4-methylnonane",
    "4-methyloctane",
    "5-methyl-2-hexanone",
    "5-methylnonane",
    "4-methyl-trans-2-pentene",
    "4-methylheptane",
    "3,3-dimethylhexane",
    "3,3-dimethylpentane",
    "3,3,5-trimethylheptane",
    "3,4-dimethylhexane",
    "3,3-diethylpentane",
    "3,3-dimethyl-2-butanone",
    "Ethyl mercaptan",
    "Ethyl methyl disulfide",
    "Ethyl Phenyl Carbonate",
    "Ethyl propyl disulfide",
    "Dimethyl sulfide",
    "Dimethyl sulfoxide",
    "Dimethyl terephthalate",
    "Dimethylacetylene",
    "Dimethylethanolamine",
    "DiPhenyl Carbonate",
    "Diethylamine",
    "Diethylene glycol",
    "Diethylenetriamine",
    "Diethylethanolamine",
    "Diisobutyl ketone",
    "Diisopropanolamine",
    "Di-n-propyl disulfide",
    "Di-n-propyl sulfide",
    "Di-sec-butyl ether",
    "Di-tert-butyl disulfide",
    "Dichloroacetaldehyde",
    "Dichloroacetyl chloride",
    "Cis-2-butene",
    "Cis-2-hexene",
    "Cis-2-pentene",
    "Cis-decahydronaphthalene",
    "Cumene",
    "Cumene hydroperoxide",
    "Ethanol",
    "Ethyl acetate",
    "Ethyl chloride",
    "Ethyl formate",
    "Diphenyl disulfide",
    "Ethane",
    "Diisopropylamine",
    "Dimethyl carbonate",
    "Dimethyl disulfide",
    "Dimethyl ether",
    "Diisopropyl ether",
    "Diisopropyl ketone",
    "DiEthyl Carbonate",
    "Diethyl disulfide",
    "Diethyl ether",
    "Diethyl sulfide",
    "Dicyclopentadiene",
    "Diethanolamine",
    "Cyclohexanone",
    "Cyclohexene",
    "Cyclopentane",
    "Di-n-butyl ether",
    "Cyclohexane",
    "Cyclohexanol",
    "Cis-1,3-dimethylcyclopentane",
    "Cis-1,4-dimethylcyclohexane",
    "M-ethyltoluene",
    "M-nitrotoluene",
    "M-xylene",
    "Maleic acid",
    "Maleic anhydride",
    "Mesitylene",
    "Isopentane",
    "Isoprene",
    "Isopropanol",
    "Isopropyl acetate",
    "Isopropyl butyl ether",
    "Isopropylcyclopentane",
    "Hydrogen chloride",
    "Hydrogen cyanide",
    "Hydrogen iodide",
    "Hydrogen sulfide",
    "Indane",
    "Indene",
    "Ethylene glycol",
    "Ethylene oxide",
    "Ethylenediamine",
    "Fluoranthene",
    "Fluorene",
    "Fluorine",
    "Ethyl tert-pentyl ether",
    "Ethylacetylene",
    "Methane",
    "Methanol",
    "Methacrylic acid",
    "Methacrylonitrile",
    "M-cresol",
    "M-cymene",
    "M-dichlorobenzene",
    "M-diethylbenzene",
    "Ketene",
    "Krypton",
    "Isobutene",
    "Isobutyl acetate",
    "Isobutyl mercaptan",
    "Isobutylbenzene",
    "Iodobenzene",
    "Isobutane",
    "Helium-4",
    "Heptanal",
    "Hexanal",
    "Hydrogen",
    "Formaldehyde",
    "Furfural",
    "Ethylcyclohexane",
    "Ethylcyclopentane",
    "Ethylene",
    "Ethylene carbonate",
    "Ethylamine",
    "Ethylbenzene",
    "N-hexyl mercaptan",
    "N-nonacosane",
    "N-nonadecane",
    "N-nonane",
    "N-butyric acid",
    "N-decane",
    "N-docosane",
    "N-dodecane",
    "N-heneicosane",
    "N-heptacosane",
    "Methylcyclohexane",
    "Methylcyclopentane",
    "Methylethanolamine",
    "Monochlorobenzene",
    "Monoethanolamine",
    "N-aminoethyl ethanolamine",
    "Methyl methacrylate",
    "Methyl n-propyl ether",
    "Methyl n-propyl sulfide",
    "Methyl Phenyl Carbonate",
    "Methyl propionate",
    "Methyl t-butyl sulfide",
    "Methyl DiEthanolAmine",
    "Methyl Ethyl Carbonate",
    "Methyl ethyl ether",
    "Methyl ethyl ketone",
    "Methyl ethyl sulfide",
    "Methyl formate",
    "N-hexacosane",
    "N-hexadecane",
    "N-hexane",
    "N-hexyl acetate",
    "N-heptadecane",
    "N-heptane",
    "N-butyl acetate",
    "N-butylbenzene",
    "N-butylcyclohexane",
    "N-butylcyclopentane",
    "N-aminoethyl piperazine",
    "N-butane",
    "Methyl tert-pentyl ether",
    "Methylacetylene",
    "Methylal",
    "Methylamine",
    "Methyl t-pentyl sulfide",
    "Methyl tert-butyl ether",
    "Methyl isobutyl ketone",
    "Methyl isopropyl ether",
    "Methyl isopropyl ketone",
    "Methyl mercaptan",
    "Methyl iodide",
    "Methyl isobutyl ether",
    "Methyl acetate",
    "Methyl chloride",
    "P-cresol",
    "P-cymene",
    "P-dichlorobenzene",
    "P-diethylbenzene",
    "P-diisopropylbenzene",
    "P-ethyltoluene",
    "Nitrous oxide",
    "O-cresol",
    "O-cymene",
    "O-dichlorobenzene",
    "O-diethylbenzene",
    "O-ethyltoluene",
    "Naphthalene",
    "Neon",
    "Neopentane",
    "Nitric acid",
    "Nitric oxide",
    "Nitrobenzene",
    "N-propyl formate",
    "N-propyl mercaptan",
    "N-propylbenzene",
    "N-propylcyclohexane",
    "N-propylcyclopentane",
    "N-tetracosane",
    "N-octacosane",
    "N-octadecane",
    "P-toluic acid",
    "P-xylene",
    "P-nitrotoluene",
    "P-phenylenediamine",
    "O-xylene",
    "Oxalic acid",
    "Oxygen",
    "Ozone",
    "O-nitrotoluene",
    "O-toluic acid",
    "Nitrogen dioxide",
    "Nitrogen tetroxide",
    "Nitrogen trioxide",
    "Nitromethane",
    "Nitroethane",
    "Nitrogen",
    "N-tridecane",
    "N-undecane",
    "N,n-dimethylacetamide",
    "N,n-dimethylformamide",
    "N-tetradecane",
    "N-tricosane",
    "N-pentadecane",
    "N-pentane",
    "N-pentyl acetate",
    "N-propyl acetate",
    "N-octane",
    "N-pentacosane",
    "Vinyl chloride",
    "Vinylacetylene",
    "Water",
    "Xenon",
    "Trans-2-butene",
    "Trans-2-hexene",
    "Trans-2-pentene",
    "Trans-decahydronaphthalene",
    "Trichloroacetaldehyde",
    "Trichloroacetyl chloride",
    "Tert-butyl mercaptan",
    "Tert-butylbenzene",
    "Tert-butylcyclohexane",
    "Tetraethylene glycol",
    "Tetrahydrofuran",
    "Thiophene",
    "Pyridine",
    "Salicylic acid",
    "Sec-butyl mercaptan",
    "Sec-butylbenzene",
    "Squalane",
    "Styrene",
    "Phenol",
    "Phosgene",
    "Phthalic acid",
    "Piperazine",
    "Propadiene",
    "Propanal",
    "Triethylamine",
    "Triethylene glycol",
    "Trimethylamine",
    "Vinyl acetate",
    "Trichloroethylene",
    "Triethanolamine",
    "Trans-1,2-dimethylcyclopentane",
    "Trans-1,3-dimethylcyclohexane",
    "Trans-1,3-dimethylcyclopentane",
    "Trans-1,4-dimethylcyclohexane",
    "Toluene",
    "Trans-1,2-dimethylcyclohexane",
    "Sulfur hexafluoride",
    "Sulfur trioxide",
    "Terephthalic acid",
    "Tert-butyl ethyl ether",
    "Sulfolane",
    "Sulfur dioxide",
    "Propionitrile",
    "Propylene",
    "Propylene carbonate",
    "Pyrene",
    "Propane",
    "Propionic acid",
    "Pentanal",
    "Phenanthrene",
    "n-Undecane",
    "NitrousOxide",
    "o-Xylene",
    "OrthoDeuterium",
    "OrthoHydrogen",
    "p-Xylene",
    "MethylPalmitate",
    "MethylStearate",
    "MM",
    "n-Butane",
    "n-Decane",
    "n-Dodecane",
    "HydrogenSulfide",
    "IsoButane",
    "IsoButene",
    "Isohexane",
    "m-Xylene",
    "MD2M",
    "CycloHexane",
    "CycloPropane",
    "D4",
    "D5",
    "D6",
    "Deuterium",
    "CoolProp",
    "Propyne",
    "ParaDeuterium",
    "ParaHydrogen",
    "n-Nonane",
    "n-Octane",
    "n-Pentane",
    "n-Propane",
    "n-Heptane",
    "n-Hexane",
    "MDM",
    "MethylLinoleate",
    "MethylLinolenate",
    "MethylOleate",
    "MD3M",
    "MD4M",
    "EthylBenzene",
    "HeavyWater",
    "Helium",
    "HFE143m",
    "DimethylCarbonate",
    "DimethylEther",
    "CarbonDioxide",
    "CarbonMonoxide",
    "CarbonylSulfide",
    "cis-2-Butene",
    "1-Butene",
    "Ammonium Peroxydisulfate",
    "Ammonium Sulfate",
    "trans-2-Butene",
    "Electrolytes",
    "Ammonium (1)",
    "Ammonium (2)",
    "R245fa",
    "R32",
    "R365MFC",
    "R404A",
    "R407C",
    "R41",
    "R141b",
    "R142b",
    "R143a",
    "R152A",
    "R161",
    "R21",
    "R116",
    "R12",
    "R123",
    "R1233zd(E)",
    "R1234yf",
    "R1234ze(E)",
    "Ammonium Chloride",
    "Ammonium Iodide",
    "Ammonium Nitrate",
    "Ammonium Perchlorate",
    "Ammonium (ion)",
    "Ammonium Bromide",
    "RC318",
    "SES36",
    "SulfurDioxide",
    "SulfurHexafluoride",
    "R410A",
    "R507A",
    "R227EA",
    "R23",
    "R236EA",
    "R236FA",
    "R218",
    "R22",
    "R125",
    "R13",
    "R134a",
    "R14",
    "R1234ze(Z)",
    "R124",
    "R11",
    "R113",
    "R114",
    "Potassium Sulfate",
    "Salt",
    "Sodium (ion)",
    "Sodium Bromide",
    "Sodium Bromide Dihydrate",
    "Sodium Carbonate (1)",
    "Potassium Carbonate (1)",
    "Potassium Carbonate (2)",
    "Potassium Carbonate (3)",
    "Potassium Carbonate (4)",
    "Potassium Chloride",
    "Potassium Hydrogen Carbonate",
    "Lithium Perchlorate",
    "Lithium Sulfate",
    "Magnesium (ion)",
    "Magnesium Bromide",
    "Magnesium Chloride",
    "Magnesium Iodide",
    "Cesium Perchlorate",
    "Cesium Sulfate",
    "Chloride (ion)",
    "Glaserite",
    "Hydron",
    "Hydroxide",
    "Bicarbonate (ion)",
    "Bisulfide (ion)",
    "Bromine (ion)",
    "Carbamate (ion)",
    "Sodium Carbonate (2)",
    "Sodium Carbonate (3)",
    "Potassium Molybdate",
    "Potassium Nitrate",
    "Potassium Nitrate (1)",
    "Potassium Perchlorate",
    "Potassium Iodide",
    "Potassium Ion",
    "Magnesium Sulfate",
    "Nitrate (ion)",
    "Perchlorate (ion)",
    "Potassium Bromide",
    "Magnesium Nitrate",
    "Magnesium Perchlorate",
    "Lithium Bromide",
    "Lithium Chloride",
    "Lithium Iodide",
    "Lithium Nitrate",
    "Iodine Ion",
    "Lithium (ion)",
    "Cesium Bromide",
    "Cesium Chloride",
    "Cesium Iodide",
    "Cesium Nitrate",
    "Carbonate (ion)",
    "Cesium (ion)",
    "Palmitate-Oleate-Linoleate (POLi)",
    "Palmitate-Oleate-Oleate (POO)",
    "Palmitate-Oleate-Palmitate (POP)",
    "Palmitate-Oleate-Stearate (POS)",
    "Palmitic Acid",
    "Sodium Palmitate",
    "1-decanol (DWSIM)",
    "1-octanol (DWSIM)",
    "1,2-propanediol (DWSIM)",
    "3-methyl-1-butanol (DWSIM)",
    "Biodiesel",
    "Sodium Nitrate",
    "Sodium Nitrate (1)",
    "Sodium Perchlorate",
    "Sodium Potassium Carbonate Hexahydrate",
    "Sodium Sulfate",
    "Sodium Sulfate (1)",
    "TriOlein (OOO)",
    "TriPalmitin (PPP)",
    "Ethyl Oleate (EtO)",
    "Ethyl Palmitate (EtP)",
    "Ethyl Stearate (EtS)",
    "Palmitate-Linoleate-Palmitate (PLiP)",
    "Ethyl Linoleate (EtLi)",
    "Sulfide (ion)",
    "DWSIM",
    "Sodium Sulfate Decahydrate",
    "Sulfate (ion)",
    "Sodium Chloride",
    "Sodium Chloride Dihydrate",
    "Sodium Hydroxide",
    "Sodium Iodide",
]

# Fast lookup
DWSIM_COMPOUND_SET = set(DWSIM_COMPOUNDS)

def is_valid_compound(name: str) -> bool:
    """Return True if name matches an entry in DWSIM_COMPOUNDS (case-sensitive)."""
    return name in DWSIM_COMPOUND_SET

def missing_compounds(names: Iterable[str]) -> list[str]:
    """Return a list of items from names that are not present in DWSIM_COMPOUNDS."""
    return [n for n in names if n not in DWSIM_COMPOUND_SET]

__all__ = ["DWSIM_COMPOUNDS", "DWSIM_COMPOUND_SET", "is_valid_compound", "missing_compounds"]
